# -*- coding: utf-8 -*-
"""Program

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tiuO07t5WIT9YJAVadsE9fb9YvDjG8p1
"""

import pandas as pd # Package to work with data

import numpy as np  # Numerical analysis package

from google.colab import drive

drive.mount("/gdrive", force_remount=True)

df = pd.read_csv('input.csv')

df['Average']=df.mean(axis=1).round(1)

df['Grade'] = pd.cut(df['Average'], bins=[0 , 39 , 49, 59, 69, 70 ,100 ], labels= ['F','E', 'D', 'C', 'B', 'A'])
df.iloc[0:11,[0,1,6,7]]
